name: Publish

on:
  push:
    branches: 
      - master
    paths-ignore:
      - '*.md'
      - '**/.gitignore'

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Ossutil
      id: cache-ossutil
      uses: actions/cache@v4
      with:
        path: ossutil64
        key: ${{ runner.os }}-ossutil64-1.7.19
      continue-on-error: true
    - name: Get Ossutil
      if: steps.cache-ossutil.outputs.cache-hit != 'true'
      run: |
        apt-get update && apt-get install -y wget unzip
        wget -q https://gosspublic.alicdn.com/ossutil/1.7.19/ossutil-v1.7.19-linux-amd64.zip
        unzip -q ossutil-v1.7.19-linux-amd64.zip
        mv ossutil-v1.7.19-linux-amd64/ossutil64 ossutil64
    - name: Config Ossutil
      run: |
        chmod +x ossutil64
        ./ossutil64 config -e ${{ secrets.ENDPOINT }} -i ${{ secrets.ACCESS_KEY_ID }} -k ${{ secrets.ACCESS_KEY_SECRET }} -L CH
    - name: Publish Svg
      run: |
        ./ossutil64 cp -f -u Status.svg oss://xzonn-images/status.svg --retry-times 3 --loglevel info
