name: Publish

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Ossutil
      id: cache-ossutil
      uses: actions/cache@v2
      with:
        path: ossutil64
        key: ${{ runner.os }}-ossutil64-1.7.7
      continue-on-error: true
    - name: Get Ossutil
      if: steps.cache-ossutil.outputs.cache-hit != 'true'
      run: |
        wget -q http://gosspublic.alicdn.com/ossutil/1.7.7/ossutil64
    - name: Config Ossutil
      run: |
        chmod +x ossutil64
        ./ossutil64 config -e ${{ secrets.ENDPOINT }} -i ${{ secrets.ACCESS_KEY_ID }} -k ${{ secrets.ACCESS_KEY_SECRET }} -L CH
    - name: Publish Svg
      run: |
        ./ossutil64 cp -f -u Status.svg oss://xzonn-images/status.svg --retry-times 3 --loglevel info
